### ISSUE TITLE
Display and edit points as unordered lists

### ISSUE THREAD

**Issue by josephmturner** [USHIN-Inc/u4few-app#33]
Displaying points as unordered lists:
- Display tag label in-line to the right of the point
- Only display tag label if it is a sub-label (in other words, do not display labels such as "Actions" or "People" but do display labels such as "Connection" or "Health") 
- In Point.js, set PointPreview css border to 0px
- In Point.js, change constants in contentExcerpt to 
```
  const contentExcerpt =
    content.length > 70 ? `${content.substring(0, 50).trim()}...` : content;
```
- Display bullet points to the left of each point in the list

Editing points as unordered lists:
- Upon clicking a point, typing cursor appears where clicked (no box opens)
- If content is greater than contentExcerpt, then while editing point, allow the text content of the point to take up more than one line
- Pressing Return creates a new point on a new line just below the existing point 

Drag events should still work on the whole PointPreview area. However, when point is being edited, text can be selected, copied, pasted, etc.

**Comment by HoldingHands** [comment]
Resolved by #43
